### ISSUE TITLE
报错AttributeError: 'ImageDraw' object has no attribute 'rounded_rectangle'

### ISSUE THREAD

**Issue by yoiyami96** [kexue-z/nonebot-plugin-heweather#1]
发送指令无法返回正确结果，如果是我犯蠢了那抱歉打扰了。日志如下：
age 1233374146 from 1986612158@[群:722970667] "天气南通"
08-06 11:12:30 [INFO] nonebot | Event will be handled by <Matcher from heweather
, type=message, priority=1, temp=False>
08-06 11:12:31 [INFO] nonebot | Matcher <Matcher from heweather, type=message, p
riority=1, temp=False> running complete
08-06 11:12:31 [ERROR] nonebot | Running matcher <Matcher from heweather, type=m
essage, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb
.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\uvicorn\main.py", line 386, in run
    server.run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\matcher.py", line 544, in run
    await handler(self, bot, event, state_)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "src/plugins\heweather\__init__.py", line 21, in _
    img = draw(data)
  File "src/plugins\heweather\convrt_pic.py", line 57, in draw
    d.rounded_rectangle([(20,20),(20+background_width,20+background_hight)], rad
ius = 40, fill = '#DBDBDB')
AttributeError: 'ImageDraw' object has no attribute 'rounded_rectangle'

**Comment by kexue-z** [comment]
PIL缺少`rounded_rectangle` 是生成圆角矩形的
建议检查一下PIL版本 `>= 8.2.0`
如果不行可以把所有的`rounded_rectangle` 替换为 `rectangle`

**Comment by yoiyami96** [comment]
> PIL缺少`rounded_rectangle` 是生成圆角矩形的
> 建议检查一下PIL版本 `>= 8.2.0`
> 如果不行可以把所有的`rounded_rectangle` 替换为 `rectangle`

更新完PIL之后日志显示找不到/data/heweather/icon100.png，但是我在按照convrt-pic.py中的路径在bot.py所在目录和插件根目录都放了图标和字体文件。convrt-pic.py中的路径如下：
if not font:
    font = str(Path("data/heweather/font.ttc").absolute())
if not icon_dir:
    icon_dir = str(Path("data/heweather/icon").absolute())

**Comment by kexue-z** [comment]
啊这，`convrt_pic.py` 的第15行应该是
```py
    icon_dir = str(Path("data/heweather/icon").absolute()) + '/'
```
少了个  `/`
最新版本号是 `0.0.5`,  应该已经修复了, 更新一下版本吧
建议使用pipy官方源更新

**Comment by yoiyami96** [comment]
> ```python
> icon_dir = str(Path("data/heweather/icon").absolute()) + '/'
> ```

更新之后依然显示FileNotFoundError: [Errno 2] No such file or directory: './data/heweather/icon100.png'，是我文件放错目录了吗😨

**Comment by kexue-z** [comment]
是我的问题😂
icon是个目录 你在.env里面指定一下目录吧
QWEATHER_ICON_DIR = "./data/heweather/icon/'

**Comment by yoiyami96** [comment]
> 是我的问题😂
> icon是个目录 你在.env里面指定一下目录吧
> QWEATHER_ICON_DIR = "./data/heweather/icon/'

可以了，大佬nb，谢谢大佬开发出这么方便的插件
