### ISSUE TITLE
Failed to import "nonebot_plugin_heweather"

### ISSUE THREAD

**Issue by chuchu404** [kexue-z/nonebot-plugin-heweather#15]
```
02-18 02:30:44  **[ERROR] nonebot | Failed to import "nonebot_plugin_htmlrender"**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\server.py", line 76, in serve
    config.load()
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Project\Qbot\robot01\.\bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\load.py", line 71, in load_all_plugins
    return manager.load_all_plugins()
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\manager.py", line 110, in load_all_plugins
    return set(
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\manager.py", line 111, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\manager.py", line 96, in load_plugin
    module = importlib.import_module(
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\manager.py", line 181, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Project\Qbot\robot01\.\src\plugins\nonebot_plugin_heweather\__init__.py", line 8, in <module>
    from .render_pic import render
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Project\Qbot\robot01\.\src\plugins\nonebot_plugin_heweather\render_pic.py", line 5, in <module>
    template_to_pic = require("nonebot_plugin_htmlrender").template_to_pic
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\load.py", line 164, in require
    plugin = get_plugin(name) or load_plugin(name)
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\load.py", line 30, in load_plugin
    return manager.load_plugin(module_path)
> File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\manager.py", line 92, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'nonebot_plugin_htmlrender'**
**02-18 02:30:44 [ERROR] nonebot | Failed to import "nonebot_plugin_heweather"**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\server.py", line 76, in serve
    config.load()
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "d:\project\qbot\robot01\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\chuchu\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Project\Qbot\robot01\.\bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\load.py", line 71, in load_all_plugins
    return manager.load_all_plugins()
  File "d:\project\qbot\robot01\venv\lib\site-packages\nonebot\plugin\manager.py", line 110, in load_all_plugins
    return set(
02-18 02:30:44 [INFO] uvicorn | Started server process [6496]
02-18 02:30:44 [INFO] uvicorn | Waiting for application startup.
02-18 02:30:44 [INFO] uvicorn | Application startup complete.
02-18 02:30:48 [INFO] uvicorn | ('127.0.0.1', 56383) - "WebSocket /onebot/v11/ws" [accepted]
    
```
apikey 普通版 正常
安装方式直接放plugins目录下
已安装pillow
咋回事啊

**Comment by kexue-z** [comment]
建议使用pip
插件使用了`nonebot-plugin-heweather` 生成图片

**Comment by chuchu404** [comment]
## AttributeError: 'Config' object has no attribute 'debug'
呜呜 我又来了，我给项目放服务器(ubuntu)上，使用您的插件时又出问题了。。。。

> 安装过程：
> 1. 使用 'nb plugin install nonebot-plugin-heweather' 安装命令
> 2. 提示 需要手动 'playwright install-deps'
> 2. 执行后报错 -> no module 'apt-pkg'
> 3. 最终网上使用[这第二个方案](https://oldtang.com/6102.html)解决并成功执行命令
> 4. 安装成功后就是目前这个问题
大佬带带孩子吧~~
~~~py
02-19 19:37:15 [SUCCESS] nonebot | ONEBOT V11 339114225 | [message.private.friend]: Message -1325126055 from 2496729202 "天气 北京"
02-19 19:37:15 [DEBUG] nonebot | Checking for matchers in priority 1...
02-19 19:37:15 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False>
02-19 19:37:15 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False>
02-19 19:37:15 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x7f455b716320>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
02-19 19:37:15 [INFO] nonebot_plugin_heweather | 使用普通版API
02-19 19:37:16 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'location': [{'name': '北京', 'id': '101010100', 'lat': '39.90498', 'lon': '116.40528', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '10', 'fxLink': 'http://hfx.link/2ax1'}, {'name': '海淀', 'id': '101010200', 'lat': '39.95607', 'lon': '116.31031', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '15', 'fxLink': 'http://hfx.link/2ay1'}, {'name': '朝阳', 'id': '101010300', 'lat': '39.92149', 'lon': '116.48641', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '15', 'fxLink': 'http://hfx.link/2az1'}, {'name': '昌平', 'id': '101010700', 'lat': '40.21808', 'lon': '116.23590', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '23', 'fxLink': 'http://hfx.link/2b31'}, {'name': '房山', 'id': '101011200', 'lat': '39.73553', 'lon': '116.13916', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '23', 'fxLink': 'http://hfx.link/2b81'}, {'name': '通州', 'id': '101010600', 'lat': '39.90248', 'lon': '116.65860', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '23', 'fxLink': 'http://hfx.link/2b21'}, {'name': '丰台', 'id': '101010900', 'lat': '39.86364', 'lon': '116.28696', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '25', 'fxLink': 'http://hfx.link/2b51'}, {'name': '大兴', 'id': '101011100', 'lat': '39.72890', 'lon': '116.33803', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '25', 'fxLink': 'http://hfx.link/2b71'}, {'name': '延庆', 'id': '101010800', 'lat': '40.46532', 'lon': '115.98500', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '33', 'fxLink': 'http://hfx.link/2b41'}, {'name': '平谷', 'id': '101011500', 'lat': '40.14478', 'lon': '117.11233', 'adm2': '北京', 'adm1': '北京市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '33', 'fxLink': 'http://hfx.link/2bb1'}], 'refer': {'sources': ['QWeather'], 'license': ['commercial license']}}
02-19 19:37:16 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-19T19:37+08:00', 'fxLink': 'http://hfx.link/2ax5', 'warning': [], 'refer': {'sources': ['12379'], 'license': ['no commercial use']}}
02-19 19:37:16 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-19T19:33+08:00', 'fxLink': 'http://hfx.link/2ax4', 'now': {'pubTime': '2022-02-19T19:00+08:00', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '9', 'no2': '6', 'so2': '2', 'co': '0.3', 'o3': '72'}, 'station': [{'pubTime': '2022-02-19T19:00+08:00', 'name': '万寿西宫', 'id': 'CNA1001', 'aqi': '24', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '16', 'pm2p5': '8', 'no2': '12', 'so2': '4', 'co': '0.4', 'o3': '74'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '定陵', 'id': 'CNA1002', 'aqi': '24', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '10', 'pm2p5': '7', 'no2': '4', 'so2': '1', 'co': '0.2', 'o3': '75'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '东四', 'id': 'CNA1003', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '15', 'pm2p5': '9', 'no2': '10', 'so2': '1', 'co': '0.2', 'o3': '68'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '天坛', 'id': 'CNA1004', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '16', 'pm2p5': '7', 'no2': '9', 'so2': '1', 'co': '0.2', 'o3': '72'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '农展馆', 'id': 'CNA1005', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '10', 'no2': '10', 'so2': '2', 'co': '0.3', 'o3': '71'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '官园', 'id': 'CNA1006', 'aqi': '21', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '8', 'no2': '7', 'so2': '3', 'co': '0.2', 'o3': '66'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '海淀区万柳', 'id': 'CNA1007', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '13', 'pm2p5': '6', 'no2': '9', 'so2': '3', 'co': '0.2', 'o3': '70'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '顺义新城', 'id': 'CNA1008', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '14', 'pm2p5': '8', 'no2': '4', 'so2': '3', 'co': '0.2', 'o3': '71'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '怀柔镇', 'id': 'CNA1009', 'aqi': '24', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '16', 'pm2p5': '9', 'no2': '7', 'so2': '2', 'co': '0.3', 'o3': '75'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '昌平镇', 'id': 'CNA1010', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '10', 'no2': '4', 'so2': '1', 'co': '0.3', 'o3': '70'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '奥体中心', 'id': 'CNA1011', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '9', 'no2': '8', 'so2': '1', 'co': '0.2', 'o3': '72'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '古城', 'id': 'CNA1012', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '19', 'pm2p5': '8', 'no2': '6', 'so2': '1', 'co': '0.2', 'o3': '70'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '延庆夏都', 'id': 'CNA3281', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '15', 'pm2p5': '8', 'no2': '2', 'so2': '1', 'co': '0.2', 'o3': '70'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '平谷新城', 'id': 'CNA3417', 'aqi': '26', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '12', 'no2': '7', 'so2': '1', 'co': '0.2', 'o3': '81'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '密云新城', 'id': 'CNA3418', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '14', 'pm2p5': '9', 'no2': '5', 'so2': '1', 'co': '0.2', 'o3': '69'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '门头沟三家店', 'id': 'CNA3671', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '16', 'pm2p5': '8', 'no2': '5', 'so2': '1', 'co': '0.1', 'o3': '70'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '丰台云岗', 'id': 'CNA3672', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '20', 'pm2p5': '7', 'no2': '2', 'so2': '1', 'co': '0.2', 'o3': '72'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '通州东关', 'id': 'CNA3673', 'aqi': '19', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '19', 'pm2p5': '9', 'no2': '8', 'so2': '1', 'co': '0.5', 'o3': '60'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '房山燕山', 'id': 'CNA3674', 'aqi': '24', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '9', 'no2': '3', 'so2': '2', 'co': '0.2', 'o3': '74'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '大兴旧宫', 'id': 'CNA3675', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '19', 'pm2p5': '7', 'no2': '5', 'so2': '4', 'co': '0.1', 'o3': '71'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '延庆石河营', 'id': 'CNA3694', 'aqi': '26', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '15', 'pm2p5': '9', 'no2': '3', 'so2': '1', 'co': '0.3', 'o3': '81'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '怀柔新城', 'id': 'CNA3695', 'aqi': '24', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '11', 'pm2p5': '7', 'no2': '2', 'so2': '3', 'co': '0.2', 'o3': '76'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '丰台小屯', 'id': 'CNA3696', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '19', 'pm2p5': '8', 'no2': '7', 'so2': '4', 'co': '0.3', 'o3': '70'}, {'pubTime': '2022-02-19T19:00+08:00', 'name': '密云镇', 'id': 'CNA3697', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '17', 'pm2p5': '10', 'no2': '5', 'so2': '4', 'co': '0.2', 'o3': '69'}], 'refer': {'sources': ['QWeather', 'CNEMC'], 'license': ['no commercial use']}}
02-19 19:37:16 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-19T19:32+08:00', 'fxLink': 'http://hfx.link/2ax1', 'now': {'obsTime': '2022-02-19T19:20+08:00', 'temp': '0', 'feelsLike': '-4', 'icon': '150', 'text': '晴', 'wind360': '270', 'windDir': '西风', 'windScale': '2', 'windSpeed': '11', 'humidity': '19', 'precip': '0.0', 'pressure': '1028', 'vis': '30', 'cloud': '10', 'dew': '-24'}, 'refer': {'sources': ['QWeather', 'NMC', 'ECMWF'], 'license': ['no commercial use']}}
02-19 19:37:16 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-19T18:35+08:00', 'fxLink': 'http://hfx.link/2ax1', 'daily': [{'fxDate': '2022-02-19', 'sunrise': '07:03', 'sunset': '17:54', 'moonrise': '20:35', 'moonset': '08:58', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '2', 'tempMin': '-9', 'iconDay': '100', 'textDay': '晴', 'iconNight': '150', 'textNight': '晴', 'wind360Day': '315', 'windDirDay': '西北风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '0', 'windDirNight': '北风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '54', 'precip': '0.0', 'pressure': '1025', 'vis': '25', 'cloud': '0', 'uvIndex': '4'}, {'fxDate': '2022-02-20', 'sunrise': '07:02', 'sunset': '17:55', 'moonrise': '21:43', 'moonset': '09:23', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '4', 'tempMin': '-6', 'iconDay': '100', 'textDay': '晴', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '225', 'windDirDay': '西南风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '315', 'windDirNight': '西北风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '36', 'precip': '0.0', 'pressure': '1025', 'vis': '25', 'cloud': '0', 'uvIndex': '4'}, {'fxDate': '2022-02-21', 'sunrise': '07:00', 'sunset': '17:57', 'moonrise': '22:52', 'moonset': '09:50', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '6', 'tempMin': '-6', 'iconDay': '100', 'textDay': '晴', 'iconNight': '150', 'textNight': '晴', 'wind360Day': '225', 'windDirDay': '西南风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '0', 'windDirNight': '北风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '31', 'precip': '0.0', 'pressure': '1030', 'vis': '25', 'cloud': '2', 'uvIndex': '4'}], 'refer': {'sources': ['QWeather', 'NMC', 'ECMWF'], 'license': ['no commercial use']}}
02-19 19:37:17 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> running complete
02-19 19:37:17 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_heweather/__init__.py", line 37, in _
    if get_driver().config.debug:
AttributeError: 'Config' object has no attribute 'debug'

~~~

**Comment by kexue-z** [comment]
啊这。。。 你在 `.env` 里加一个 `DEBUG=false`
