### ISSUE TITLE
下载到根目录无法使用

### ISSUE THREAD

**Issue by lancer-wang** [kexue-z/nonebot-plugin-heweather#18]
`03-30 11:46:04 [ERROR] nonebot | Failed to import "nonebot_plugin_heweather"
Traceback (most recent call last):
  File "/cobudy/omega-miya/bot.py", line 57, in <module>
    nonebot.load_plugin("nonebot_plugin_heweather")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 984, in load_plugin
    return context.run(_load_plugin, manager, module_path)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 155, in load_plugin
    return importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/cobudy/omega-miya/nonebot_plugin_heweather/__init__.py", line 4, in <module>
    from nonebot.adapters.onebot.v11 import Bot, MessageEvent, MessageSegment
  File "/usr/local/lib/python3.9/dist-packages/nonebot/adapters/onebot/__init__.py", line 1, in <module>
    from .v11 import Bot as V11Bot
  File "/usr/local/lib/python3.9/dist-packages/nonebot/adapters/onebot/v11/__init__.py", line 16, in <module>
    from .adapter import Adapter as Adapter
  File "/usr/local/lib/python3.9/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 9, in <module>
    from nonebot.exception import WebSocketClosed
ImportError: cannot import name 'WebSocketClosed' from 'nonebot.exception' (/usr/local/lib/python3.9/dist-packages/nonebot/exception.py)
`

**Comment by kexue-z** [comment]
那为什么不看文档呢
