### ISSUE TITLE
出现连接失败的问题，apikey本地测试也没问题

### ISSUE THREAD

**Issue by NeoChen-MMZ** [kexue-z/nonebot-plugin-heweather#3]
使用时出现了的httpx.ConnectTimeout
和风天气的apikey在本地测试后也没问题
如果是我犯蠢了还请包涵QAQ

> QWEATHER_APIKEY = xxx

本地的httpx版本为0.19.0
以下为报错信息
`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\message.py", line 155, in _run_matcher
    await matcher.run(bot, event, state)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\matcher.py", line 584, in run
    await handler(self, bot, event, self.state)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\__init__.py", line 36, in _
    data = await get_City_Weather(city)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\get_weather.py", line 33, in get_City_Weather
    city_info = await get_Location(city)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\get_weather.py", line 16, in get_Location
    res = await client.get(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1740, in get
    return await self.request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1494, in request
    response = await self.send(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 276, in handle_async_request
    (
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
`

**Comment by NeoChen-MMZ** [comment]
`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_backends\anyio.py", line 154, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
 File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\message.py", line 155, in _run_matcher
    await matcher.run(bot, event, state)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\matcher.py", line 584, in run
    await handler(self, bot, event, self.state)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\__init__.py", line 36, in _
    data = await get_City_Weather(city)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\get_weather.py", line 33, in get_City_Weather
    city_info = await get_Location(city)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\get_weather.py", line 16, in get_Location
    res = await client.get(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1740, in get
    return await self.request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1494, in request
    response = await self.send(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 276, in handle_async_request
    (
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
`

**Comment by NeoChen-MMZ** [comment]
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_backends\anyio.py", line 154, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\message.py", line 155, in _run_matcher
    await matcher.run(bot, event, state)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\matcher.py", line 584, in run
    await handler(self, bot, event, self.state)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\__init__.py", line 36, in _
    data = await get_City_Weather(city)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\get_weather.py", line 33, in get_City_Weather
    city_info = await get_Location(city)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\nonebot_plugin_heweather\get_weather.py", line 16, in get_Location
    res = await client.get(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1740, in get
    return await self.request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1494, in request
    response = await self.send(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 276, in handle_async_request
    (
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\nonebot\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

**Comment by kexue-z** [comment]
`httpx.ConnectTimeout`

应该是网络问题,,,你自己在相同环境下写一个httpx的插件看看行不行...或者是代理等问题

**Comment by NeoChen-MMZ** [comment]
好的麻烦了，我自己再排查一下
