### ISSUE TITLE
The operation did not complete (read) (_ssl.c:997)

### ISSUE THREAD

**Issue by SnowMoonSS** [kexue-z/nonebot-plugin-heweather#33]
神秘，也没改什么东西，怎么就不能用了……会不会是和风天气的api发生了变动……
```
10-10 09:27:21 [SUCCESS] nonebot | ONEBOT V11 1234567890 | [message.group.normal]: Message 1905501708 from 123456789@[群:123456789] "深圳天气"
10-10 09:27:21 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False>
10-10 09:27:21 [INFO] nonebot_plugin_heweather | 使用普通版API
10-10 09:27:27 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> running complete
10-10 09:27:27 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/home/snowmoonss/.pyenv/versions/3.10.6/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/anyio/streams/tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "/home/snowmoonss/.pyenv/versions/3.10.6/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 66, in start_tls
    with anyio.fail_after(timeout):
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 64, in start_tls
    with map_exceptions(exc_map):
  File "/home/snowmoonss/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 64, in start_tls
    with map_exceptions(exc_map):
  File "/home/snowmoonss/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/snowmoonss/.pyenv/versions/alice/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout
```

**Comment by kexue-z** [comment]
不清楚 `v0.6.1` 可以正常使用，建议先排除是否是本机环境问题
