### ISSUE TITLE
为什么安装不了啊

### ISSUE THREAD

**Issue by lyk1205** [kexue-z/nonebot-plugin-heweather#5]
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-heweather (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-heweather
WARNING: Ignoring invalid distribution -onebot2 (/usr/local/lib/python3.8/dist-packages)

**Comment by kexue-z** [comment]
请提供完整的日志和输入的指令

**Comment by lyk1205** [comment]
> 请提供完整的日志和输入的指令

pip install nonebot-plugin-heweather
WARNING: Ignoring invalid distribution -onebot2 (/usr/local/lib/python3.8/dist-packages)
WARNING: Ignoring invalid distribution -onebot2 (/usr/local/lib/python3.8/dist-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-heweather (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-heweather
WARNING: Ignoring invalid distribution -onebot2 (/usr/local/lib/python3.8/dist-packages)
![image](https://user-images.githubusercontent.com/84303774/142192395-e290fdba-5653-4529-825e-c951262066c8.png)

**Comment by kexue-z** [comment]
试试 `pip install -i https://mirrors.aliyun.com/pypi/simple/ nonebot-plugin-heweather`

**Comment by lyk1205** [comment]
> 试试 `pip install -i https://mirrors.aliyun.com/pypi/simple/ nonebot-plugin-heweather`

试过的
pip install -i https://mirrors.aliyun.com/pypi/simple/ nonebot-plugin-heweather
WARNING: Ignoring invalid distribution -onebot2 (/usr/local/lib/python3.8/dist-packages)
WARNING: Ignoring invalid distribution -onebot2 (/usr/local/lib/python3.8/dist-packages)
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-heweather (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-heweather
WARNING: Ignoring invalid distribution -onebot2 (/usr/local/lib/python3.8/dist-packages)

**Comment by kexue-z** [comment]
哦 我知道，是你的python版本太低。 你可以试试`git clone` 把 `nonebot_plugin_heweather` 文件夹放入你的插件目录中

**Comment by lyk1205** [comment]
> 哦 我知道，是你的python版本太低。 你可以试试`git clone` 把 `nonebot_plugin_heweather` 文件夹放入你的插件目录中
3.8也不可以吗

**Comment by kexue-z** [comment]
只需要`pillow` 和 `httpx` 就能运行 直接把源代码放进插件目录中就能跑了

**Comment by lyk1205** [comment]
> 只需要`pillow` 和 `httpx` 就能运行 直接把源代码放进插件目录中就能跑了

图标背景需要自己创建文件夹放进去吗

**Comment by lyk1205** [comment]
> 只需要`pillow` 和 `httpx` 就能运行 直接把源代码放进插件目录中就能跑了

你好，能问下这个什么情况吗
11-17 20:14:57 [DEBUG] nonebot | CQHTTP | Calling API send_msg
11-17 20:14:57 [DEBUG] nonebot | Running CalledAPI hooks...
11-17 20:14:57 [INFO] nonebot | Matcher <Matcher from heweather, type=message, priority=1, temp=False> running complete
11-17 20:14:57 [ERROR] nonebot | Running matcher <Matcher from heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/handler.py", line 64, in __call__
    await self.func(
  File "/home/lyk/qqbot/lyk_bot/lyk_bot/plugins/heweather/__init__.py", line 51, in _
    await weather.finish(MessageSegment.image(b64))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 520, in finish
    await bot.send(event=event, message=_message, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/bot.py", line 471, in send
    return await self.send_msg(**params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/bot.py", line 416, in call_api
    return await super().call_api(api, **data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/_bot.py", line 172, in call_api
    raise exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/_bot.py", line 155, in call_api
    result = await self._call_api(api, **data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/bot.py", line 369, in _call_api
    raise ApiNotAvailable
nonebot.adapters.cqhttp.exception.ApiNotAvailable

**Comment by kexue-z** [comment]
这个是。。。你的cqhttp没有正常启动吧
