### ISSUE TITLE
请求数据过大，读取超时

### ISSUE THREAD

**Issue by yuexps** [kexue-z/nonebot-plugin-heweather#72]
系统：Ubuntu 22.04 x64
阿里云ECS 2核2G
Python 3.10

09-22 14:03:04 [SUCCESS] nonebot | QQ 102069799 | [C2C_MESSAGE_CREATE]: Message ROBOT1.0_wpKUl06PNM3l.mADTY1ko2m.JgN.NJR4GKxhvHTPIxsDb6NF2HNx.C2IHWWkQ5xoUjBNq8cXFL5HRC8yri2QaA!! from 6BFA44D5AFC72685E3CCD630D06F79C6: [Text(type='text', data={'text': '天气 重庆'})]
09-22 14:03:04 [DEBUG] nonebot | Checking for matchers in priority 1...
09-22 14:03:04 [DEBUG] nonebot | Plugin-Alconna | Alconna::天气 对 "天气 重庆" 的解析结果是 (matched=True, header_match=(origin='天气' result='天气' matched=True groups={}), main_args={'city': '重庆'})
09-22 14:03:04 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_heweather, lineno=30)
09-22 14:03:04 [DEBUG] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_heweather, lineno=30)
09-22 14:03:04 [DEBUG] nonebot | Running handler Dependent(call=_)
09-22 14:03:04 [INFO] nonebot_plugin_heweather | 使用免费订阅API
09-22 14:03:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'location': [{'name': '重庆', 'id': '101040100', 'lat': '29.56376', 'lon': '106.55046', 'adm2': '重庆', 'adm1': '重庆市', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '11', 'fxLink': 'https://www.qweather.com/weather/chongqing-101040100.html'}], 'refer': {'sources': ['QWeather'], 'license': ['QWeather Developers License']}}
09-22 14:03:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2024-09-22T13:58+08:00', 'fxLink': 'https://www.qweather.com/en/air/chongqing-101040100.html', 'now': {'pubTime': '2024-09-22T13:00+08:00', 'aqi': '32', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '32', 'pm2p5': '20', 'no2': '17', 'so2': '9', 'co': '0.7', 'o3': '83'}, 'station': [{'pubTime': '2024-09-22T13:00+08:00', 'name': '缙云山', 'id': 'CNA1414', 'aqi': '26', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '26', 'pm2p5': '11', 'no2': '29', 'so2': '16', 'co': '0.5', 'o3': '78'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '天生', 'id': 'CNA1416', 'aqi': '47', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '47', 'pm2p5': '25', 'no2': '28', 'so2': '8', 'co': '0.6', 'o3': '69'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '两路', 'id': 'CNA1417', 'aqi': '34', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '34', 'pm2p5': '12', 'no2': '20', 'so2': '7', 'co': '0.6', 'o3': '94'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '虎溪', 'id': 'CNA1418', 'aqi': '45', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '42', 'pm2p5': '31', 'no2': '20', 'so2': '10', 'co': '0.5', 'o3': '95'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '南坪', 'id': 'CNA1419', 'aqi': '33', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '31', 'pm2p5': '23', 'no2': '16', 'so2': '7', 'co': '0.5', 'o3': '71'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '唐家沱', 'id': 'CNA1420', 'aqi': '29', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '22', 'pm2p5': '7', 'no2': '12', 'so2': '5', 'co': '0.6', 'o3': '92'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '茶园', 'id': 'CNA1421', 'aqi': '30', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '30', 'pm2p5': '11', 'no2': '14', 'so2': '6', 'co': '0.5', 'o3': '93'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '白市驿', 'id': 'CNA1422', 'aqi': '34', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '34', 'pm2p5': '12', 'no2': '22', 'so2': '10', 'co': '0.6', 'o3': '102'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '空港', 'id': 'CNA1425', 'aqi': '31', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '27', 'pm2p5': '15', 'no2': '14', 'so2': '8', 'co': '0.8', 'o3': '99'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '新山村', 'id': 'CNA1426', 'aqi': '28', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '19', 'pm2p5': '19', 'no2': '22', 'so2': '6', 'co': '0.7', 'o3': '79'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '礼嘉', 'id': 'CNA1427', 'aqi': '27', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '19', 'pm2p5': '18', 'no2': '18', 'so2': '8', 'co': '0.7', 'o3': '86'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '蔡家', 'id': 'CNA1428', 'aqi': '35', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '26', 'pm2p5': '24', 'no2': '23', 'so2': '7', 'co': '0.6', 'o3': '84'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '鱼新街', 'id': 'CNA1429', 'aqi': '25', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '25', 'pm2p5': '12', 'no2': '27', 'so2': '6', 'co': '0.4', 'o3': '62'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '歇台子', 'id': 'CNA3014', 'aqi': '31', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '31', 'pm2p5': '16', 'no2': '15', 'so2': '8', 'co': '0.7', 'o3': '73'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '龙井湾', 'id': 'CNA3015', 'aqi': '43', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '43', 'pm2p5': '19', 'no2': '14', 'so2': '10', 'co': '0.6', 'o3': '83'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '上清寺', 'id': 'CNA3133', 'aqi': '28', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '28', 'pm2p5': '12', 'no2': '27', 'so2': '6', 'co': '0.8', 'o3': '74'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '安康', 'id': 'CNA3346', 'aqi': '39', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '31', 'pm2p5': '27', 'no2': '14', 'so2': '5', 'co': '0.6', 'o3': '48'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '北山路', 'id': 'CNA3347', 'aqi': '45', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '35', 'pm2p5': '31', 'no2': '17', 'so2': '11', 'co': '0.8', 'o3': '95'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '人民东路', 'id': 'CNA3349', 'aqi': '42', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '38', 'pm2p5': '29', 'no2': '7', 'so2': '6', 'co': '0.6', 'o3': '56'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '滩子口', 'id': 'CNA3350', 'aqi': '26', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '20', 'pm2p5': '18', 'no2': '11', 'so2': '6', 'co': '0.5', 'o3': '59'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '棠香', 'id': 'CNA3351', 'aqi': '35', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '23', 'pm2p5': '20', 'no2': '6', 'so2': '9', 'co': '0.6', 'o3': '109'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '迎宾大道', 'id': 'CNA3353', 'aqi': '53', 'level': '2', 'category': '良', 'primary': 'PM2.5', 'pm10': '37', 'pm2p5': '37', 'no2': '18', 'so2': '4', 'co': '0.8', 'o3': '75'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '百安坝', 'id': 'CNA3356', 'aqi': '29', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '28', 'pm2p5': '20', 'no2': '13', 'so2': '12', 'co': '0.4', 'o3': '57'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '芙蓉中路', 'id': 'CNA3482', 'aqi': '24', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '24', 'pm2p5': '10', 'no2': '7', 'so2': '5', 'co': '0.4', 'o3': '73'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '行政中心', 'id': 'CNA3484', 'aqi': '43', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '43', 'pm2p5': '15', 'no2': '18', 'so2': '10', 'co': '0.7', 'o3': '102'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '高寺路', 'id': 'CNA3485', 'aqi': '23', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '23', 'pm2p5': '15', 'no2': '10', 'so2': '4', 'co': '0.7', 'o3': '61'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '书院路', 'id': 'CNA3599', 'aqi': '48', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '35', 'pm2p5': '33', 'no2': '15', 'so2': '10', 'co': '0.7', 'o3': '110'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '虎峰', 'id': 'CNA3600', 'aqi': '51', 'level': '2', 'category': '良', 'primary': 'PM10', 'pm10': '52', 'pm2p5': '14', 'no2': '16', 'so2': '8', 'co': '0.7', 'o3': '88'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '龙门街', 'id': 'CNA3601', 'aqi': '43', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '34', 'pm2p5': '30', 'no2': '13', 'so2': '15', 'co': '0.7', 'o3': '105'}, {'pubTime': '2024-09-22T13:00+08:00', 'name': '昌元', 'id': 'CNA3610', 'aqi': '49', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '42', 'pm2p5': '34', 'no2': '13', 'so2': '10', 'co': '0.6', 'o3': '102'}], 'refer': {'sources': ['中国环境监测总站 (CNEMC)'], 'license': ['CC BY-SA 4.0']}}
09-22 14:03:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2024-09-22T13:59+08:00', 'fxLink': 'https://www.qweather.com/en/weather/chongqing-101040100.html', 'now': {'obsTime': '2024-09-22T13:54+08:00', 'temp': '28', 'feelsLike': '30', 'icon': '104', 'text': '阴', 'wind360': '225', 'windDir': '西南风', 'windScale': '1', 'windSpeed': '4', 'humidity': '62', 'precip': '0.0', 'pressure': '984', 'vis': '30', 'cloud': '93', 'dew': '21'}, 'refer': {'sources': ['QWeather'], 'license': ['CC BY-SA 4.0']}}
09-22 14:03:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2024-09-22T13:59+08:00', 'fxLink': 'https://www.qweather.com/en/weather/chongqing-101040100.html', 'daily': [{'fxDate': '2024-09-22', 'sunrise': '06:43', 'sunset': '18:52', 'moonrise': '21:35', 'moonset': '11:05', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '32', 'tempMin': '26', 'iconDay': '104', 'textDay': '阴', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '135', 'windDirDay': '东南风', 'windScaleDay': '1-3', 'windSpeedDay': '3', 'wind360Night': '90', 'windDirNight': '东风', 'windScaleNight': '1-3', 'windSpeedNight': '3', 'humidity': '71', 'precip': '0.0', 'pressure': '975', 'vis': '24', 'cloud': '25', 'uvIndex': '2'}, {'fxDate': '2024-09-23', 'sunrise': '06:43', 'sunset': '18:51', 'moonrise': '22:25', 'moonset': '12:14', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '33', 'tempMin': '26', 'iconDay': '101', 'textDay': '多云', 'iconNight': '150', 'textNight': '晴', 'wind360Day': '90', 'windDirDay': '东风', 'windScaleDay': '1-3', 'windSpeedDay': '3', 'wind360Night': '90', 'windDirNight': '东风', 'windScaleNight': '1-3', 'windSpeedNight': '3', 'humidity': '61', 'precip': '0.0', 'pressure': '973', 'vis': '25', 'cloud': '25', 'uvIndex': '7'}, {'fxDate': '2024-09-24', 'sunrise': '06:44', 'sunset': '18:49', 'moonrise': '23:20', 'moonset': '13:20', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '35', 'tempMin': '27', 'iconDay': '100', 'textDay': '晴', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '45', 'windDirDay': '东北风', 'windScaleDay': '1-3', 'windSpeedDay': '3', 'wind360Night': '90', 'windDirNight': '东风', 'windScaleNight': '1-3', 'windSpeedNight': '3', 'humidity': '57', 'precip': '0.0', 'pressure': '972', 'vis': '25', 'cloud': '25', 'uvIndex': '7'}], 'refer': {'sources': ['QWeather'], 'license': ['CC BY-SA 4.0']}}
09-22 14:03:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2024-09-22T14:00+08:00', 'fxLink': 'https://www.qweather.com/severe-weather/chongqing-101040100.html', 'warning': [{'id': '10104010020240916175113120533617', 'sender': '重庆市气象局', 'pubTime': '2024-09-16T17:51+08:00', 'title': '重庆市气象台发布森林草原火险红色预警', 'startTime': '2024-09-16T17:51+08:00', 'endTime': '2024-09-23T23:59+08:00', 'status': 'update', 'level': '红色', 'severity': 'Extreme', 'severityColor': 'Red', 'type': '1041', 'typeName': '森林（草原）火险', 'urgency': '', 'certainty': '', 'text': '重庆市森林草原防灭火指挥部、重庆市应急管理局、重庆市林业局、重庆市气象局2024年9月16日18时继续联合发布“森林草原火险红色预警信号”。我市万州、黔江、涪陵、大渡口、江北、沙坪坝、九龙坡、南岸、北碚、渝北、巴南、长寿、江津、合川、永川、南川、綦江、大足、璧山、铜梁、潼南、荣昌、开州、梁平、武隆、城口、丰都、垫江、忠县、云阳、奉节、巫山、巫溪、石柱、秀山、酉阳、彭水、重庆高新区、万盛经开区等地已连续多日出现高或极高森林草原火险气象等级。预计9月17日至23日上述区县仍将持续高或极高森林草原火险气象等级，发生森林草原火灾的风险极高。', 'related': '10104010020240906174953610950350'}], 'refer': {'sources': ['国家预警信息发布中心 (12379)'], 'license': ['CC BY-SA 4.0']}}
09-22 14:03:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2024-09-22T13:59+08:00', 'fxLink': 'https://www.qweather.com/en/weather/chongqing-101040100.html', 'hourly': [{'fxTime': '2024-09-22T15:00+08:00', 'temp': '30', 'icon': '104', 'text': '阴', 'wind360': '149', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '11', 'humidity': '54', 'pop': '7', 'precip': '0.0', 'pressure': '977', 'cloud': '77', 'dew': '20'}, {'fxTime': '2024-09-22T16:00+08:00', 'temp': '31', 'icon': '104', 'text': '阴', 'wind360': '145', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '11', 'humidity': '54', 'pop': '7', 'precip': '0.0', 'pressure': '977', 'cloud': '62', 'dew': '20'}, {'fxTime': '2024-09-22T17:00+08:00', 'temp': '32', 'icon': '104', 'text': '阴', 'wind360': '143', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '11', 'humidity': '54', 'pop': '7', 'precip': '0.0', 'pressure': '977', 'cloud': '47', 'dew': '20'}, {'fxTime': '2024-09-22T18:00+08:00', 'temp': '31', 'icon': '104', 'text': '阴', 'wind360': '140', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '11', 'humidity': '56', 'pop': '7', 'precip': '0.0', 'pressure': '976', 'cloud': '54', 'dew': '20'}, {'fxTime': '2024-09-22T19:00+08:00', 'temp': '30', 'icon': '104', 'text': '阴', 'wind360': '68', 'windDir': '东风', 'windScale': '1-3', 'windSpeed': '9', 'humidity': '58', 'pop': '7', 'precip': '0.0', 'pressure': '976', 'cloud': '62', 'dew': '20'}, {'fxTime': '2024-09-22T20:00+08:00', 'temp': '29', 'icon': '104', 'text': '阴', 'wind360': '57', 'windDir': '东北风', 'windScale': '1-3', 'windSpeed': '9', 'humidity': '58', 'pop': '7', 'precip': '0.0', 'pressure': '975', 'cloud': '69', 'dew': '20'}, {'fxTime': '2024-09-22T21:00+08:00', 'temp': '29', 'icon': '151', 'text': '多云', 'wind360': '55', 'windDir': '东北风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '60', 'pop': '7', 'precip': '0.0', 'pressure': '976', 'cloud': '68', 'dew': '20'}, {'fxTime': '2024-09-22T22:00+08:00', 'temp': '28', 'icon': '151', 'text': '多云', 'wind360': '56', 'windDir': '东北风', 'windScale': '1-3', 'windSpeed': '5', 'humidity': '62', 'pop': '7', 'precip': '0.0', 'pressure': '976', 'cloud': '67', 'dew': '20'}, {'fxTime': '2024-09-22T23:00+08:00', 'temp': '28', 'icon': '151', 'text': '多云', 'wind360': '72', 'windDir': '东风', 'windScale': '1-3', 'windSpeed': '5', 'humidity': '63', 'pop': '7', 'precip': '0.0', 'pressure': '976', 'cloud': '66', 'dew': '20'}, {'fxTime': '2024-09-23T00:00+08:00', 'temp': '28', 'icon': '151', 'text': '多云', 'wind360': '118', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '5', 'humidity': '66', 'pop': '7', 'precip': '0.0', 'pressure': '977', 'cloud': '77', 'dew': '20'}, {'fxTime': '2024-09-23T01:00+08:00', 'temp': '27', 'icon': '151', 'text': '多云', 'wind360': '146', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '69', 'pop': '7', 'precip': '0.0', 'pressure': '977', 'cloud': '89', 'dew': '21'}, {'fxTime': '2024-09-23T02:00+08:00', 'temp': '27', 'icon': '151', 'text': '多云', 'wind360': '147', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '72', 'pop': '7', 'precip': '0.0', 'pressure': '977', 'cloud': '100', 'dew': '21'}, {'fxTime': '2024-09-23T03:00+08:00', 'temp': '27', 'icon': '151', 'text': '多云', 'wind360': '133', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '72', 'pop': '7', 'precip': '0.0', 'pressure': '977', 'cloud': '97', 'dew': '21'}, {'fxTime': '2024-09-23T04:00+08:00', 'temp': '27', 'icon': '151', 'text': '多云', 'wind360': '120', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '70', 'pop': '7', 'precip': '0.0', 'pressure': '976', 'cloud': '94', 'dew': '20'}, {'fxTime': '2024-09-23T05:00+08:00', 'temp': '26', 'icon': '151', 'text': '多云', 'wind360': '111', 'windDir': '东风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '70', 'pop': '7', 'precip': '0.0', 'pressure': '975', 'cloud': '91', 'dew': '20'}, {'fxTime': '2024-09-23T06:00+08:00', 'temp': '26', 'icon': '151', 'text': '多云', 'wind360': '105', 'windDir': '东风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '72', 'pop': '7', 'precip': '0.0', 'pressure': '974', 'cloud': '94', 'dew': '20'}, {'fxTime': '2024-09-23T07:00+08:00', 'temp': '26', 'icon': '101', 'text': '多云', 'wind360': '199', 'windDir': '南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '70', 'pop': '7', 'precip': '0.0', 'pressure': '973', 'cloud': '97', 'dew': '20'}, {'fxTime': '2024-09-23T08:00+08:00', 'temp': '27', 'icon': '101', 'text': '多云', 'wind360': '190', 'windDir': '南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '68', 'pop': '7', 'precip': '0.0', 'pressure': '972', 'cloud': '100', 'dew': '20'}, {'fxTime': '2024-09-23T09:00+08:00', 'temp': '27', 'icon': '101', 'text': '多云', 'wind360': '167', 'windDir': '南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '64', 'pop': '7', 'precip': '0.0', 'pressure': '971', 'cloud': '99', 'dew': '19'}, {'fxTime': '2024-09-23T10:00+08:00', 'temp': '28', 'icon': '101', 'text': '多云', 'wind360': '132', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '7', 'humidity': '59', 'pop': '7', 'precip': '0.0', 'pressure': '972', 'cloud': '98', 'dew': '19'}, {'fxTime': '2024-09-23T11:00+08:00', 'temp': '29', 'icon': '101', 'text': '多云', 'wind360': '113', 'windDir': '东南风', 'windScale': '1-3', 'windSpeed': '9', 'humidity': '56', 'pop': '7', 'precip': '0.0', 'pressure': '972', 'cloud': '97', 'dew': '19'}, {'fxTime': '2024-09-23T12:00+08:00', 'temp': '30', 'icon': '101', 'text': '多云', 'wind360': '106', 'windDir': '东风', 'windScale': '1-3', 'windSpeed': '9', 'humidity': '51', 'pop': '7', 'precip': '0.0', 'pressure': '973', 'cloud': '66', 'dew': '18'}, {'fxTime': '2024-09-23T13:00+08:00', 'temp': '32', 'icon': '101', 'text': '多云', 'wind360': '102', 'windDir': '东风', 'windScale': '1-3', 'windSpeed': '9', 'humidity': '47', 'pop': '7', 'precip': '0.0', 'pressure': '973', 'cloud': '34', 'dew': '18'}, {'fxTime': '2024-09-23T14:00+08:00', 'temp': '33', 'icon': '101', 'text': '多云', 'wind360': '97', 'windDir': '东风', 'windScale': '1-3', 'windSpeed': '9', 'humidity': '45', 'pop': '7', 'precip': '0.0', 'pressure': '974', 'cloud': '3', 'dew': '18'}], 'refer': {'sources': ['QWeather'], 'license': ['CC BY-SA 4.0']}}
09-22 14:03:09 [DEBUG] nonebot | QQ | Bot 102069799 calling API post_c2c_files
09-22 14:03:25 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_heweather, lineno=30) running complete
09-22 14:03:25 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_heweather, lineno=30) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot_plugin_heweather/__init__.py", line 53, in _
    await UniMessage.image(raw=img).send()
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot_plugin_alconna/uniseg/message.py", line 997, in send
    res = await fn.send_to(target, bot, msg)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot_plugin_alconna/uniseg/adapters/qq/exporter.py", line 265, in send_to
    return await bot.send(
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 496, in send
    return await self.send_to_c2c(
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 405, in send_to_c2c
    media_info = await self.post_c2c_files(
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/adapter.py", line 423, in _call_api
    return await api_handler(bot, **data)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/utils.py", line 64, in __call__
    return await self.func(inst, *args, **kwds)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 1700, in post_c2c_files
    return type_validate_python(PostC2CFilesReturn, await self._request(request))
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 551, in _request
    return self._handle_response(response)
  File "/root/ikaros-bot/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 540, in _handle_response
    raise ActionFailed(response)
nonebot.adapters.qq.exception.ActionFailed: <ActionFailed: 400, code=10998, message=请求数据过大，读取超时, trace_id=e204fb7928f8d7c732ec56e932559c8d>

**Comment by kexue-z** [comment]
playwright 截图发过去的图片太大了。与本项目无关
